apiVersion: apps/v1
kind: Deployment
metadata:
  name:  {{.Values.appName}}
spec:
  replicas:  {{.Values.replicas}}
  selector:
    matchLabels:
      app:  {{.Values.appName}}
  template:
    metadata:
      labels:
        app:  {{.Values.appName}}
    spec:
      containers:
      - name:  {{.Values.appName}}-container
        image: tapiwanashembizvo/config-server:10
        ports:
        - containerPort: 8888
        env:
        - name:  DB_URL
          valueFrom:
            secretKeyRef:
              name:  {{.Values.postgresSecret}}
              key:  DB_URL
        

        - name:  DB_PASS
          valueFrom:
            secretKeyRef:
              name:   {{.Values.postgresSecret}}
              key: DB_PASS

        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name:  {{.Values.postgresSecret}}
              key: DB_USER
        resources:
          requests:
            memory: "50Mi" #memory is messured in Mi and Gi 
            cpu: "150m" #1000m  = 1 cpu core 
          
          limits:
            memory: "200Mi"
            cpu: "500m"
      
    
