apiVersion: v1
kind: Service
metadata:
  name: {{.Values.appName}}-service
spec:
  type: ClusterIP
  selector:
    app: {{.Values.appName}}
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
  
