apiVersion: apps/v1
kind: Deployment
metadata:
  name:  {{.Values.appName}}-load-balancer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{.Values.appName}}
  template:
    metadata:
      labels:
        app:  {{.Values.appName}}
    spec:
      containers:
      - name:  {{.Values.appName}}
        image: nginx:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "50Mi"
            cpu: "150m"
          limits:
            memory: "150Mi"
            cpu: "250m"
        volumeMounts:
        - name:  {{.Values.configMap}}
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
      volumes:
      - name: {{.Values.configMap}}
        configMap:
          name: {{.Values.configMap}}
