apiVersion: v1
kind: Service
metadata:
  name: {{.Values.appName}}-service
spec:
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 30905
  selector:
    app: {{.Values.appName}}