apiVersion: v1
kind: Service
metadata:
  name: nice-app-service
spec:
  type: ClusterIP
  selector:
    app: {{.Values.appName}}
  ports:
    - protocol: TCP
      port: 8778
      targetPort: 8778
  
